stages:
  - build
  - test
  - coverage

variables:
  CMAKE_BUILD_TYPE: Debug
  BUILD_DIR: build
  COVERAGE_OUTPUT: coverage.info
  LCOV_OPTS: "--rc lcov_branch_coverage=1"

default:
  image: debian:trixie

before_script:
  - apt-get update -qq && apt-get install -y cmake lcov ninja-build libsdl3-dev build-essential git
  - mkdir -p ${BUILD_DIR}

build:
  stage: build
  script:
    - cmake -B ${BUILD_DIR} -G Ninja -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
             -DCMAKE_CXX_FLAGS="--coverage -O0 -g"
             -DCMAKE_C_FLAGS="--coverage -O0 -g"
    - cmake --build ${BUILD_DIR}
  artifacts:
    paths:
      - ${BUILD_DIR}/mveplayer

test:
  stage: test
  script:
    - ${BUILD_DIR}/tests/mve_tests
  artifacts:
    when: always
    reports:
      junit: ${BUILD_DIR}/test-results.xml
    paths:
      - ${BUILD_DIR}/*.gcno
      - ${BUILD_DIR}/*.gcda

coverage:
  stage: coverage
  script:
    - lcov ${LCOV_OPTS} --capture --directory ${BUILD_DIR} --output-file ${COVERAGE_OUTPUT}
    - lcov ${LCOV_OPTS} --remove ${COVERAGE_OUTPUT} '/usr/*' --output-file ${COVERAGE_OUTPUT}
    - genhtml ${COVERAGE_OUTPUT} --output-directory coverage-html
  coverage: '/lines\.+: (\d+\.\d+)%/'
  artifacts:
    paths:
      - ${COVERAGE_OUTPUT}
      - coverage-html/
    expire_in: 7 days
